<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAsArray($key, $order, $search=null){
        $qry = $this->createQueryBuilder('p');
        if (!empty($search)) {
            $qry->where('p.title LIKE :search')
                ->setParameter('search','%'.$search.'%');
        }
        $qry = $qry->addOrderBy('p.'.$key, $order)
            ->getQuery();
        //dump($qry->getSQL());
        return $qry->getArrayResult();
    }
}
